quakes<- datasets::quakes
summary(quakes)
plot(quakes)
plot(quakes$depth,type='l')
plot(quakes$depth,type='p')
plot(quakes$depth, type='p',xlab='Ozone concentration',ylab='No of instances',main='Earth quakes',col='blue')
barplot(quakes$depth,horiz='T',axes='T')
barplot(quakes$mag, main='ozone concentration in the air',ylab='ozone levels',horiz='T',axes='T',col='blue')
hist(quakes$mag,col='yellow')
hist(quakes$depth,col='grey')
boxplot(quakes$mag,main ='Boxplot')
boxplot.stats(quakes$stations)$out
boxplot(quakes[,0:4],main='multiple box plots')
par(mfrow=c(3,3),mar=c(2,5,2,1),las=0,bty='o')
plot(quakes$long,quakes$mag)
plot(quakes$depth,type='l')
plot(quakes$mag,type='l')
plot(quakes$stations,type='l')
barplot(quakes$depth,main = 'Barplot',ylab ='frequency',horiz='F',axes='T') 
hist(quakes$depth,main='Histogram',col='violet')
barplot(quakes$mag,main='Barplot',ylab='frequency',horiz='F',axes='T')        
sd(quakes$depth)
sd(airquality$Wind)
sd(airquality$Ozone,na.rm = 'T')
var(quakes$depth)
var(airquality$Ozone,na.rm = 'T')
skewness(quakes$depth)
kurtosis(quakes$depth)
